"""Initial migration.

Revision ID: 95bfa4348f62
Revises: 
Create Date: 2024-07-15 14:02:43.830495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bfa4348f62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Visits', schema=None) as batch_op:
        batch_op.drop_column('VisitDateTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('VisitDateTime', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
